config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get '/demo' => :demo, on: :collection
  end
  resources :teams do
    resources :players
    resources :events
    resources :messages
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # belongs_to :player
  # belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :team

  validates :game, presence: true
  validates :start_time, presence: true
end

app/models/managing.rb
class Managing < ApplicationRecord
  belongs_to :user
  belongs_to :team
  validates :team_id, uniqueness: { scope: :user_id }
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team

   mount_uploader :avatar, AvatarUploader

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}".squeeze(' ').strip.titleize
  end
end

app/models/receiving.rb
class Receiving < ApplicationRecord
  belongs_to :messages
  belongs_to :user
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :users
  has_many   :managings, dependent: :destroy
  has_many   :users, through: :managings

  has_many   :players, dependent: :destroy
  has_many   :events, dependent: :destroy

  validates  :name, presence: true

  def team_name
    "#{name}".squeeze(' ').strip.titleize
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :managings, dependent: :destroy
  has_many :managed_teams, through: :managings, source: :team

  has_secure_password

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    uniqueness: { case_sensitive: false },
                    format:     VALID_EMAIL_REGEX
  def full_name
    "#{first_name} #{last_name}".squeeze(' ').strip.titleize
  end

  private

  def set_defaults
    self.admin ||= false
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_team
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  # GET /events
  # GET /events.json
  def index
    @team = Team.find params[:team_id]
    @events = @team.events.order(start_time: :desc)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find params[:id]
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        @team.events << @event
        format.html { redirect_to team_event_url(@team, @event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to team_events_path(@team), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    event = Event.find params[:id]
    @team = Team.find params[:team_id]
    event.destroy
    respond_to do |format|
      format.html { redirect_to team_events_path(@team), notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:game, :start_time)
    end

    def find_team
      @team = Team.find params[:team_id] if params[:team_id]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!

  def new
    @team = Team.new
  end

  def index
    @teams = current_user.managed_teams.order(created_at: :desc)
  end

  def show
    @team = Team.find params[:id]
  end

  def create
    @team = Team.new team_params
    if @team.save
      @team.users << current_user
      redirect_to teams_path, notice: 'Team Created'
    else
      flash[:alert] = 'Please fix errors below'
      render '/teams'
    end
  end

  def destroy
    team = Team.find params[:id]
    team.destroy
    redirect_to teams_path
  end

  def team_params
    params.require(:team).permit(:name)
  end

  private

  def find_team
    @team = Team.find params[:id]
  end

  def find_params
    params.require(:team).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thanks for signing up'
    else
      flash[:alret] = 'Fix errors below'
      render :new
    end
  end

  def show
    @user = User.find params[:id]

  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managings_helper.rb
module ManagingsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for([@team, event]) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div <div class="input-field col s12">
      <%= f.label :game %>
      <%= f.text_field :game %>
    </div>
      <%= f.label :start_time %>
      <%= f.datetime_local_field :start_time %>
    </div>
  </div>
    <button class="btn waves-effect waves-light" type="submit" name="action">Add Event
       <i class="material-icons right"></i>
    </button>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', team_event_path(@team, @event) %> |
<%= link_to 'Back', team_events_path(@team) %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.game %></td>
        <td><%= event.start_time %></td>
        <td class='btn waves-effect waves-light'><%= link_to 'Show', team_event_path(@team, event) %></td>
        <td class='btn waves-effect waves-light'><%= link_to 'Edit', edit_team_event_path(@team, event) %></td>
        <td class='btn waves-effect waves-light'><%= link_to 'Destroy', team_event_path(@team, event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<a href="<%= team_players_path(@team)  %>" class="btn waves-effect waves-light" type="submit" name="action">Back
   <i class="material-icons right"></i>
</a>

<br>

<%= link_to 'New Event', new_team_event_path(@team) %>
<%= month_calendar do |date| %>
  <%= date %>
<% end %>

<!-- <%= month_calendar events: @events do |date, meetings| %>
  <%= date %>

  <% @events.each do |event| %>
    <div>
      <%= event.game %>
    </div>
  <% end %>
<% end %> -->

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', team_events_path(@team) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @event.game %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<%= link_to 'Edit', edit_team_event_path(@team, @event) %> |
<%= link_to 'Back', team_events_path(@team) %>

app/views/users/demo.html.erb
<div class="parallax-container">
   <div class="parallax"><%= image_tag image_path('image1.jpg') %></div>
</div>
<div class="section white">
      <h2 class="header">Soccer Assist</h2>
      <p class="grey-text text-darken-3 lighten-3">Soccer assist is your ideal app for building your team </p>
      <p class="grey-text text-darken-3 lighten-3">and sharing information with parents.</p>
</div>
<div class="parallax-container">
  <div class="parallax"><%= image_tag image_path('image3.jpg') %></div>
</div>
<div class="section white">
     <h2 class="header">Thank you for choosing Soccer Assist</h2>
     <h3 class="grey-text text-darken-3 lighten-3">
       Created by: Ron Shalevich</p>
</div>
<div class="parallax-container">
  <div class="parallax"><%= image_tag image_path('image2.jpg') %></div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= @user.errors.full_messages.join(", ") %>
<%= form_for @user do |f| %>
<div class="row">
  <div class="input-field col s6">
    <i class ="material-icons prefix">account_circle</i>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="input-field col s6">
    <i class ="material-icons prefix">account_circle</i>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
</div>
<div class="row">
  <div class="input-field col s6">
    <i class="material-icons prefix">phone</i>
    <%= f.label :phone_number %>
    <%= f.number_field :phone_number %>
  </div>
  <div class="input-field col s6">
    <i class="material-icons prefix">email</i>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
</div>
  <div class="input-field col s12">
    <i class ="material-icons prefix">lock</i>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="input-field col s12">
    <i class ="material-icons prefix">lock</i>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <button class="btn waves-effect waves-light" type="submit" name="action">Sign Up
     <i class="material-icons right"></i>
  </button>
  <% end %>
  <br>
  <br>
  <a href="<%= demo_users_path  %>" class="btn waves-effect waves-light" type="submit" name="action">Learn More
     <i class="material-icons right"></i>
  </a>

app/views/users/show.html.erb
<h1>in show page</h1>
<%= @team.errors.full_messages.join(", ")  %>
<%= form_for [@user, @team] do |f| %>
  <div>
    <%= f.text_field :body %>
  </div>
  <%= f.submit %>
<% end %>

<h2>team</h2>
<% @user.teams.each do |team| %>
  <%= team.name %>
  <%= link_to "delete", user_team_path(@user, team),
                        method: :delete,
                        data: {confirm: "Are you sure?"} %>
  <hr>
<% end %>