config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get '/demo' => :demo, on: :collection
  end
  resources :teams do
    resources :players
    resources :events
    resources :messages
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # belongs_to :player
  # belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :team

  validates :game, presence: true
  validates :start_time, presence: true
end

app/models/managing.rb
class Managing < ApplicationRecord
  belongs_to :user
  belongs_to :team
  validates :team_id, uniqueness: { scope: :user_id }
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team

   mount_uploader :avatar, AvatarUploader

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}".squeeze(' ').strip.titleize
  end
end

app/models/receiving.rb
class Receiving < ApplicationRecord
  belongs_to :messages
  belongs_to :user
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :users
  has_many   :managings, dependent: :destroy
  has_many   :users, through: :managings

  has_many   :players, dependent: :destroy
  has_many   :events, dependent: :destroy

  validates  :name, presence: true

  def team_name
    "#{name}".squeeze(' ').strip.titleize
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :managings, dependent: :destroy
  has_many :managed_teams, through: :managings, source: :team

  has_secure_password

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    uniqueness: { case_sensitive: false },
                    format:     VALID_EMAIL_REGEX
  def full_name
    "#{first_name} #{last_name}".squeeze(' ').strip.titleize
  end

  private

  def set_defaults
    self.admin ||= false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :find_team
  before_action :find_player, only: [:edit]

  def new
    @player = Player.new
    @player.avatar = params[:file]
  end

  def create
    @player = Player.new player_params
    @team = Team.find params[:team_id]
    if @player.save
      @team.players << @player
      redirect_to team_players_path(@team), notice: 'Player Created'
    else
      flash[:alert] = 'Please fix errors below'
    end
  end

  def index
    @team = Team.find params[:team_id]
    @players = @team.players.order(jersey_number: :desc)
  end

  def edit
  end

  def update
    @player = Player.find params[:id]
    @player.avatar = params[:file]
    if @player.update params.require(:player).permit(:first_name,
                                                     :last_name,
                                                     :jersey_number,
                                                     :position,
                                                     :parent,
                                                     :avatar)
      redirect_to team_player_path(@team, @player)
    else
      render :edit
    end
  end

  def destroy
    player = Player.find params[:id]
    @team = Team.find params[:team_id]
    player.destroy
    redirect_to team_players_path(@team)
  end

  def player_params
    params.require(:player).permit(:first_name,
                                   :last_name,
                                   :jersey_number,
                                   :position,
                                   :parent,
                                   :avatar)
  end

  def show
    @player = Player.find params[:id]
  end

  private

  def find_player
    @player = Player.find params[:id]
  end

  def find_team
    @team = Team.find params[:team_id] if params[:team_id]
  end

  def find_params
    params.require(:player).permit(:first_name,
                                   :last_name,
                                   :jersey_number)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!

  def new
    @team = Team.new
  end

  def index
    @teams = current_user.managed_teams.order(created_at: :desc)
  end

  def show
    @team = Team.find params[:id]
  end

  def create
    @team = Team.new team_params
    if @team.save
      @team.users << current_user
      redirect_to teams_path, notice: 'Team Created'
    else
      flash[:alert] = 'Please fix errors below'
      render '/teams'
    end
  end

  def destroy
    team = Team.find params[:id]
    team.destroy
    redirect_to teams_path
  end

  def team_params
    params.require(:team).permit(:name)
  end

  private

  def find_team
    @team = Team.find params[:id]
  end

  def find_params
    params.require(:team).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thanks for signing up'
    else
      flash[:alret] = 'Fix errors below'
      render :new
    end
  end

  def show
    @user = User.find params[:id]

  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managings_helper.rb
module ManagingsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/players/_form.html.erb
<%= form_for [@team, @player] do |f| %>
<div class="input-field col s6">
  <%= f.label  :first_name  %>
  <%= f.text_field :first_name %>
</div>
<div class="input-field col s6">
  <%= f.label  :last_name  %>
  <%= f.text_field :last_name %>
</div>
<div class="input-field col s6">
  <%= f.label  :jersey_number  %>
  <%= f.number_field :jersey_number %>
</div>
<div class="input-field col s6">
  <%= f.label  :position  %>
  <%= f.text_field :position %>
</div>
<div class="input-field col s6">
  <%= f.label  :parent  %>
  <%= f.text_field :parent %>
</div>
<div class='btn waves-effect waves-light'>
   <%= f.file_field :avatar %>
</div>
<div class="input-field col s3">
  <button class="btn waves-effect waves-light" type="submit" name="action">Add Player
     <i class="material-icons right"></i>
  </button><% end %>
</div>

app/views/players/edit.html.erb
<h1>Update Player</h1>
<%= render 'form' %>

app/views/players/index.html.erb
<h1>Your Team</h1>
<div class="collection">
  <% @players.each do |player| %>
  <div class="collection-item">
    <%= image_tag player.avatar_url(:thumb) if player.avatar? %>
    <%= link_to player.full_name, team_player_path(current_team, player) %>
  </div>
  <% end %>
</div>
<br><br>
<div class="buttons">
  <a href="<%= new_team_player_path(current_team)  %>" class="btn waves-effect waves-light" type="submit" name="action">Add Player
     <i class="material-icons right"></i>
  </a>
</div>

app/views/players/new.html.erb
<h1>Build your Player</h1>
<%= render 'form' %>

app/views/players/show.html.erb
<div class="row">
    <div class="card-panel hoverable">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Hi <%= current_player.full_name %></span>
          <p>
            Jersey: <%= current_player.jersey_number %>
          </p>
          <p id='picture'><%= image_tag current_player.avatar %></p>
          <p> Position: <%= current_player.position %></p>
          <p> Parent: <%= current_player.parent %></p>
        </div>
        <div class="card-action">
          <%= link_to 'Remove Player', team_player_path(@team, current_player), method: :delete %>
            |
          <%= link_to 'Back', team_players_path %>
            |
          <%= link_to 'Edit Player', edit_team_player_path(@team, current_player) %>
        </div>
      </div>
    </div>
</div>


      <!-- <div class="carousel carousel-slider center" data-indicators="true">
          <div class="carousel-fixed-item center">
            <a class="btn waves-effect white grey-text darken-text-2">button</a>
          </div>
          <div class="carousel-item red white-text" href="#one!">
            <h2>First Panel</h2>
            <p class="white-text">This is your first panel</p>
          </div>
          <div class="carousel-item amber white-text" href="#two!">
            <h2>Second Panel</h2>
            <p class="white-text">This is your second panel</p>
          </div>
          <div class="carousel-item green white-text" href="#three!">
            <h2>Third Panel</h2>
            <p class="white-text">This is your third panel</p>
          </div>
          <div class="carousel-item blue white-text" href="#four!">
            <h2>Fourth Panel</h2>
            <p class="white-text">This is your fourth panel</p>
          </div>
        </div> -->