config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get '/demo' => :demo, on: :collection
  end
  resources :teams do
    resources :players
    resources :events
    resources :messages
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # belongs_to :player
  # belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :team

  validates :game, presence: true
  validates :start_time, presence: true
end

app/models/managing.rb
class Managing < ApplicationRecord
  belongs_to :user
  belongs_to :team
  validates :team_id, uniqueness: { scope: :user_id }
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team

   mount_uploader :avatar, AvatarUploader

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}".squeeze(' ').strip.titleize
  end
end

app/models/receiving.rb
class Receiving < ApplicationRecord
  belongs_to :messages
  belongs_to :user
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :users
  has_many   :managings, dependent: :destroy
  has_many   :users, through: :managings

  has_many   :players, dependent: :destroy
  has_many   :events, dependent: :destroy

  validates  :name, presence: true

  def team_name
    "#{name}".squeeze(' ').strip.titleize
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :managings, dependent: :destroy
  has_many :managed_teams, through: :managings, source: :team

  has_secure_password

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    uniqueness: { case_sensitive: false },
                    format:     VALID_EMAIL_REGEX
  def full_name
    "#{first_name} #{last_name}".squeeze(' ').strip.titleize
  end

  private

  def set_defaults
    self.admin ||= false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managings_helper.rb
module ManagingsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Soccer</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-top">
    <nav>
      <div class="nav-wrapper">
        <div class="brand-logo right">
          <a href="<%= demo_users_path  %>">
            <%= image_tag image_path('fire-ball.jpg') %>
          </a>
        </div>
        <ul class='left'>
          <li class='tab col s2'><%= link_to "Home", root_path %></li>
          <% if current_team.present? %>
            <li class='tab col s2'><%= link_to "Players", team_players_path(@team)  %></li>
            <li class='tab col s2'><%= link_to "Calendar", team_events_path(@team) %></li>
            <li class='tab col s2'><%= link_to "Communication", new_team_message_path(@team) %></li>
          <%  else  %>
            <li class='tab col s2 disabled'><%= link_to "Players"  %></li>
            <li class='tab col s2 disabled'>  <%= link_to "Calendar" %></li>
            <li class='tab col s2 disabled'>  <%= link_to "Communication" %></li>
          <% end %>
          <% if user_signed_in? %>
            Welcome <%= current_user.first_name %>
            <li class='tab col s2'>  <%= link_to "Sign Out", sessions_path, method: :delete %></li>
          <% else %>
            <li class='tab col s2'><%= link_to "Sign Up", new_user_path %></li>
            <li class='tab col s2'>  <%= link_to "Sign In", new_session_path %></li>
          <% end %>
        </ul>
      </div>
      </div>
    </nav>
  </div>
  <div class="team">
    <div id="name">
    <% if current_team.present? %>
      <%= link_to current_team.name, team_players_path(@team) %>
    <% end %>
  </div>
  </div>
    <div class="container-side">
      <div class="col s12 m2 l2">
    </div>
    </div>
    <div class="container-main">
      <div class="col s12 m10 l10">
        <%= yield %>
        <%= render 'layouts/nav_bar' %>
      </div>
    </div>
  </body>
</html>